"""add FK constraints to vitals_records

Revision ID: 59a3c98baebc
Revises: 6ae8d087838d
Create Date: 2026-04-16 05:23:34.625840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a3c98baebc'
down_revision: Union[str, None] = '6ae8d087838d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'vitals_records', 'wearable_devices', ['device_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'vitals_records', 'patients', ['patient_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vitals_records', type_='foreignkey')
    op.drop_constraint(None, 'vitals_records', type_='foreignkey')
    # ### end Alembic commands ###
