"""add vitals_records table

Revision ID: 6ae8d087838d
Revises: b3588609bda6
Create Date: 2026-04-16 05:21:59.504676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae8d087838d'
down_revision: Union[str, None] = 'b3588609bda6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vitals_records',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('blood_oxygen', sa.SmallInteger(), nullable=False),
    sa.Column('heart_beat', sa.SmallInteger(), nullable=False),
    sa.Column('stress', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('critical_reason', sa.String(length=100), nullable=True),
    sa.Column('record_id', sa.String(length=50), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('ack_state', sa.Enum('pending', 'acknowledged', 'failed', name='ack_state'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('essential_vitals_only', sa.Boolean(), nullable=False),
    sa.Column('buffered_during_dead_zone', sa.Boolean(), nullable=False),
    sa.Column('backfill_batch_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id')
    )
    op.create_index(op.f('ix_vitals_records_backfill_batch_id'), 'vitals_records', ['backfill_batch_id'], unique=False)
    op.create_index(op.f('ix_vitals_records_device_id'), 'vitals_records', ['device_id'], unique=False)
    op.create_index(op.f('ix_vitals_records_patient_id'), 'vitals_records', ['patient_id'], unique=False)
    op.create_index(op.f('ix_vitals_records_timestamp'), 'vitals_records', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vitals_records_timestamp'), table_name='vitals_records')
    op.drop_index(op.f('ix_vitals_records_patient_id'), table_name='vitals_records')
    op.drop_index(op.f('ix_vitals_records_device_id'), table_name='vitals_records')
    op.drop_index(op.f('ix_vitals_records_backfill_batch_id'), table_name='vitals_records')
    op.drop_table('vitals_records')
    # ### end Alembic commands ###
